global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'epr-mcp-server'
    static_configs:
      - targets: ['epr-mcp-server:8000']
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']